### ISSUE TITLE
organise selection?

### ISSUE THREAD

**Issue by mardtendebakker** [mardtendebakker/nsk#1048]
can we have some button NEXT TO STATUS to SORT the confirmed and unconfirmed in the users menu? So i can sort on confirmed for the copiatek users?
If i have to find an employee i have to scroll through all unconfirmed people

![Image](https://github.com/user-attachments/assets/c072e9c3-7909-4185-aa4b-4be16ae2b57b)

![Image](https://github.com/user-attachments/assets/6afa4a14-654d-4a8c-b1cf-53f65d9618de)

**Comment by luxferoo** [comment]
Sure @mardtendebakker

**Comment by mardtendebakker** [comment]
In That case Shayan Should remove illigal users
And limit the registration for externals

Op di 10 dec. 2024 11:00 schreef imam harir ***@***.***>:

**Comment by shayank** [comment]
perfect, I will do it 👍

**Comment by mardtendebakker** [comment]
great
also this is a good reason not to go with services from aws. limitations,
limitations

Met vriendelijke groet,
Mardten de Bakker

Willem II-Laan 39
6371 JB Landgraaf
06 27394143


Op di 10 dec 2024 om 11:25 schreef Shayan Karami ***@***.***>:
