### ISSUE TITLE
store_publisher role improvment

### ISSUE THREAD

**Issue by luxferoo** [mardtendebakker/nsk#1049]
There are some **Forbidden resource** errors for the store_publisher role
I think it would be good to check with Mardten which resources store_publisher should have access to.

**Comment by mardtendebakker** [comment]
StockItems as the publisher needs to approve the items before it is
published to store or the user must define the stockitems to a different
status like "To Approve" so the webstore publisher can check and approve
items before sent to magento
Per haps in a later stage we can define this approval process and handling
better when tasks are developed.

I created this status already
[image: image.png]

All items within menuitem Webshop
[image: image.png]

All salesorders and further handling (shipping) created by Magento

[image: image.png]

Met vriendelijke groet,
Mardten de Bakker

Willem II-Laan 39
6371 JB Landgraaf
06 27394143


Op vr 6 dec 2024 om 11:45 schreef imam harir ***@***.***>:

**Comment by mardtendebakker** [comment]
it is becoming more clear we need to have roles and permissions worked out better but not in cognito
