### ISSUE TITLE
admin settings

### ISSUE THREAD

**Issue by shayank** [mardtendebakker/nsk#253]
- [x] #199 
- [x] #210 
- [x] #216 
- [x] #236 
- [x] #240
- [x] #239
- [x] #254
- [x] #255
- [x] #256
- [x] #257
- [x] #263 
- [x] #269
- [x] #281 
- [x] #295 
- [x] #314
- [x] #315
- [x] #602 
- [x] #606 
- [x] #622 
- [x] #624 
- [x] manage users group

**Comment by mardtendebakker** [comment]
currently anyone can register and start doing stuff in Nexxus. That is quite dangerous.
Per haps 1st restriction email must be from copiatek.nl
If not then it must be approved before able to log in

**Comment by shayank** [comment]
I think that is really great idea.
