### ISSUE TITLE
logistics pick up display map

### ISSUE THREAD

**Issue by luxferoo** [mardtendebakker/nsk#270]

**Comment by mardtendebakker** [comment]
this looks good.
I am just wondering how the route calculation is done. We can talk about it on tuesday

**Comment by luxferoo** [comment]
@mardtendebakker sure, I'm using the ptv API by sending waypoints in a specific order and then they return the path

**Comment by mardtendebakker** [comment]
I see
Normaly you send zipcodes and housenumbers
The pvt program calculates the best route to drive
That is now not the case

Op zo 9 jul. 2023 19:26 schreef imam harir ***@***.***>:

**Comment by luxferoo** [comment]
@mardtendebakker I see, I'll explain in details what've done and why and then do the needed changes after our meeting
