### ISSUE TITLE
no quantity in SO

### ISSUE THREAD

**Issue by mardtendebakker** [mardtendebakker/nsk#446]
When I put all saleable items in a salesorder, the quantity is 0 after saving. That is confusing.
After let's say take out 1 article from a product sku, then the counting is messed up.

ie. 1 producttype has 4 articles. I put 4 articles in the so. quantity is 0. then i remove 2 and set it to 2. Quantity is -2

![image](https://github.com/mardtendebakker/nsk/assets/126237209/cc199b4e-bd4b-4140-b1e8-ce032d630085)

**Comment by luxferoo** [comment]
Hi @mardtendebakker @shayank, I reproduce it in dev en aswell

expected:
![1](https://github.com/mardtendebakker/nsk/assets/17208637/93a684eb-76ee-4744-8675-33a3afac517f)

result:
![2](https://github.com/mardtendebakker/nsk/assets/17208637/63f5f3c0-07e8-478a-ba6f-8a99b5c37c51)

**Comment by mardtendebakker** [comment]
if a product has status In Stock then quantity in SO is visible.
if a product has status For Sale then quantity in SO becomes 0

In the future:
if a product has status in Stock then it is not saleable untill all tasks are done but only if tasks are designated to that producttype. It will then get the status For Sale automagically

**Comment by mardtendebakker** [comment]
adding products which has quantity 1
adding products which has quantity 20

result


![Image](https://github.com/mardtendebakker/nsk/assets/126237209/2435523c-451f-4585-9832-2bd685a694ce)
