### ISSUE TITLE
Adjust time in calendar logistics.

### ISSUE THREAD

**Issue by mardtendebakker** [mardtendebakker/nsk#485]

**Comment by mardtendebakker** [comment]
when planning PO or SO the default duration is 1 hour.
We should be able to plan a delivery time and a duration.
Currently planning more than 6 pick up will make other pickups invisible

Creating a field with duration will free up space in the calender I think.

**Comment by mardtendebakker** [comment]
![image](https://github.com/mardtendebakker/nsk/assets/126237209/21fd576c-1524-4276-b628-b02ace69596f)
1 day has 14 PO's but only 6 are visible. On 1 day we should be able to see multiple cars next to eachother.
Because how will you see 10 cars driving on 1 day? Or even 50? Per haps then a dropdowm on top of the column?

**Comment by mardtendebakker** [comment]
![image](https://github.com/mardtendebakker/nsk/assets/126237209/07ae27cf-c2c4-47ba-853a-0cc61d9e7f00)

**Comment by luxferoo** [comment]
@mardtendebakker  @shayank what do you think about adding a duration or an estimated delivery date field ? Is it possible now ?

**Comment by shayank** [comment]
@mardtendebakker @luxferoo I think we can close this if it's already implemented?

**Comment by mardtendebakker** [comment]
hi guys, it looks pretty awesome 🙂

________________________________
Van: Shayan Karami ***@***.***>
Verzonden: zondag 1 oktober 2023 18:45
Aan: mardtendebakker/nsk ***@***.***>
CC: mardtendebakker ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [mardtendebakker/nsk] Adjust time in calendar logistics. (Issue #485)


@mardtendebakker<https://github.com/mardtendebakker> @luxferoo<https://github.com/luxferoo> I think we can close this if it's already implemented?
