### ISSUE TITLE
logistic calendar view improvment

### ISSUE THREAD

**Issue by shayank** [mardtendebakker/nsk#522]
update hover effect reduce the transparency.
handle overlap for 1 car of 1 hrs.
minimum 30 minutes, instead of 1 hour.

related issues:
- [x] #485

**Comment by shayank** [comment]
30 minutes example:

![Image](https://github.com/mardtendebakker/nsk/assets/122120643/487ad6fe-3e8b-45b2-ab80-5f1f5bb95e36)

as you can see in the image.
pickup1: 10:00
pickup2: 10:45
do not have overlap.

**Comment by mardtendebakker** [comment]
that would be wonderfull
Something else is fishy, 2023008502 is planned at 9:30 but in the calendar it is 09:00

**Comment by shayank** [comment]
@mardtendebakker 
I think we can also close #485
