### ISSUE TITLE
show error message to client

### ISSUE THREAD

**Issue by luxferoo** [mardtendebakker/nsk#528]
What is it about please ? we normally show an error message in case the action fails.

Oh, OK. I was see that on 422 error duplicate entry, when I wanted to add a product to sale order.

![Image](https://user-images.githubusercontent.com/122120643/268503934-e19a5fdb-2e8b-4ca7-839c-f902d6509fd2.png)

and 403 e.g:

![Image](https://user-images.githubusercontent.com/122120643/268625100-fb77f2a9-e607-4a97-9ce8-2ef6522f2734.png)

maybe next to (x) 403 toast message.

**Comment by shayank** [comment]
@luxferoo 
I think we should show server message when we have any kind of error regardless of translation.
because usually we should not have any error.
this way just helps the developer to fix unhanded situation.

**Comment by shayank** [comment]
@luxferoo 

![Image](https://github.com/mardtendebakker/nsk/assets/122120643/a15fee02-a78f-47ca-8536-9f650c4fa1df)

still I can not see the server error

**Comment by shayank** [comment]
@luxferoo 

here for example, email is required and you can see the message in network log,
we want to see the message in the red error box after error code (in this case 400)

![Image](https://github.com/mardtendebakker/nsk/assets/122120643/17e96bc7-186c-40b0-9c00-ef3b7b0e4e5f)
