### ISSUE TITLE
partner in order list is not clickable

### ISSUE THREAD

**Issue by luxferoo** [mardtendebakker/nsk#550]
What should the click do please ? Partner page doesn't exist in the app btw

good, question. all partners are customers, so after clicking on partner user should navigate to contacts/customers/:id page

**Comment by mardtendebakker** [comment]
Actually i think it makes sense to have a 3rd option in contacts
Customer, supplier, partner

Op ma 25 sep. 2023 21:40 schreef imam harir ***@***.***>:

**Comment by shayank** [comment]
@luxferoo  
Mardten is right. but separating partner needs refactoring. we will do it in the future.
For this task we can consider a partner is always a customer.
