### ISSUE TITLE
can not create new attribute

### ISSUE THREAD

**Issue by mardtendebakker** [mardtendebakker/nsk#622]

**Comment by mardtendebakker** [comment]
Also missing the fromtype.label

![Image](https://github.com/mardtendebakker/nsk/assets/126237209/e63dc1b4-cbd4-454d-a6d4-b2c2b02b6caf)

**Comment by mardtendebakker** [comment]
![Image](https://github.com/mardtendebakker/nsk/assets/126237209/84370666-dd0b-4c63-bccb-d3712725c3e8)

**Comment by luxferoo** [comment]
Hi @mardtendebakker @shayank , I didn't notice the issue was assigned to Shayan so I started investigating and I saw that attributes + other admin resources are missing "post endpoints". I also created this PR https://github.com/mardtendebakker/nsk/pull/623 to add create attribute endpoint

**Comment by luxferoo** [comment]
@shayank @mardtendebakker I also added missing post endpoints https://github.com/mardtendebakker/nsk/pull/625

**Comment by shayank** [comment]
Thanks @luxferoo
@mardtendebakker  changes are deployed and ready!
