### ISSUE TITLE
Product location division

### ISSUE THREAD

**Issue by shayank** [mardtendebakker/nsk#626]
- [x] #632 
- [x] #634
- [x] #636 
- [x] #640

like IKEA (investigate)

building blabla

> rack 2 compartment 18

> rack 2 compartment 17

we might go with parent-child data structure to have dynamic compartment

**Comment by mardtendebakker** [comment]
we dont need a 3th option ourselfs but per haps it is a good thing to prepare anyway for other companies.

for instance
rack 2 shell 3 compartment 1
________________________________
Van: Shayan Karami ***@***.***>
Verzonden: maandag 16 oktober 2023 13:37
Aan: mardtendebakker/nsk ***@***.***>
CC: Subscribed ***@***.***>
Onderwerp: [mardtendebakker/nsk] Product location division (Issue #626)


like IKEA (investigate)

building blabla

rack 2 compartment 18

rack 2 compartment 17
