### ISSUE TITLE
infinite loop while clicking on main menu too fast

### ISSUE THREAD

**Issue by shayank** [mardtendebakker/nsk#79]
issue reproduction scenario:
you are on purchases page for example.
click on customers page menu and then purchases page menu very quickly (before loading complete).

**Comment by shayank** [comment]
http://ec2-107-23-95-236.compute-1.amazonaws.com/

**Comment by luxferoo** [comment]
Thanks @shayank I reproduce it ! I think it's related with the feature that make the url replaced with the page number by default, I'll check that
