### ISSUE TITLE
show deliveries

### ISSUE THREAD

**Issue by mardtendebakker** [mardtendebakker/nsk#817]
show supplier was working. after update not working

![Image](https://github.com/mardtendebakker/nsk/assets/126237209/810727cc-8a3c-425a-9a9a-f24cc8486611)

**Comment by shayank** [comment]
![Image](https://github.com/mardtendebakker/nsk/assets/122120643/e0c4ce54-7851-4977-80fe-22c8f2cb777d)

I can see it is working
can you check it one more time please

**Comment by mardtendebakker** [comment]
[image: image.png]
Met vriendelijke groet,
Mardten de Bakker

Willem II-Laan 39
6371 JB Landgraaf
06 27394143


Op do 21 mrt 2024 om 15:36 schreef Shayan Karami ***@***.***>:

**Comment by mardtendebakker** [comment]
![image](https://github.com/mardtendebakker/nsk/assets/126237209/c640034f-684f-4155-bfdd-f031999aebf6)
