### ISSUE TITLE
print label

### ISSUE THREAD

**Issue by shayank** [mardtendebakker/nsk#823]

**Comment by mardtendebakker** [comment]
1. category: Producttype
2. typenummer of Device, Modelnumber or serialnumber
3. Production year (if known)
4. Name + address of tester Copiatek + signature of actual employee/logged in user. Can be a stored PNG to print on paper
5. Result of test, date of testing + outcome result for device
6. The Nature of the tests (monitor visual aspect) PC (can use a part of wipereport) same for mobile devices, smartphones, tablets etc.
