### ISSUE TITLE
print package

### ISSUE THREAD

**Issue by shayank** [mardtendebakker/nsk#837]

**Comment by shayank** [comment]
We already have 5 different type of pdf export

we need to have a new printing named **package**

backend side:
it is similar to OrderPrinting except:
we need to drop the price column and add a new column **Test** with value **Ok**

frontend side:
We already have a print button for order printing.
The button should change to a dropdown button, 
We can keep the old one as an option named **normal**
And new one for package printing named **package**
_A dropdown similar to product printing_

@Saidakl can take the backend part
@EdsonHalubets3 can take the frontend part

**Comment by mardtendebakker** [comment]
This is the official example from the government for a test report. it needs my name and signature. It is for the declaration and also for testreport. It should be connected to the correct labels.

[Testrapport+_2_.pdf](https://github.com/mardtendebakker/nsk/files/14721129/Testrapport%2B_2_.pdf)

**Comment by mardtendebakker** [comment]
how it looks when filled in

[Testrapport+ingevuld.pdf](https://github.com/mardtendebakker/nsk/files/14721287/Testrapport%2Bingevuld.pdf)

**Comment by mardtendebakker** [comment]
also please call the form  declaration-export.pdf

A packingslip or packageslip is something else which we also need  :)

**Comment by Saidakl** [comment]
Mardten, do we need everything to be like the testrapport? The declarations, date of test, kind of test etc everything?

**Comment by mardtendebakker** [comment]
Yes because it is also used as declaration

Op vr 22 mrt. 2024 15:49 schreef Saidakl ***@***.***>:
