### ISSUE TITLE
server error on search product multiple times

### ISSUE THREAD

**Issue by shayank** [mardtendebakker/nsk#936]

**Comment by shayank** [comment]
@luxferoo , @mardtendebakker 
I investigated about it.
I found that the error is from the db.
We had the same problem before.
I increased the db size but it didn't work. I think the best solution for now is to try to optimize the query.

**Comment by shayank** [comment]
@luxferoo
I think this one worst to try:
https://github.com/users/mardtendebakker/projects/1/views/1?pane=issue&itemId=54887825
Because it will remove one extra query. what do you think?

**Comment by shayank** [comment]
@luxferoo 
very interesting, I did not notice that, yes, you right, after 3rd time.
maybe prisma auto optimization query logic like cache... maybe.
I will investigate more.

**Comment by luxferoo** [comment]
thanks brother @shayank
